name: Release
permissions:
  contents: write

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        fetch-tags: true
    - uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6.0.0
    - uses: actions/setup-node@v6
      with:
        node-version: 22.x
        cache: 'pnpm'
    - run: pnpm i
    - run: pnpm test
    - run: pnpm lint
    - run: pnpm audit --production
    - run: pnpm build
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: >-
        bash .github/workflows/release.sh ${{ github.ref_name }}
